### ISSUE TITLE
test - things todo

### ISSUE THREAD

**Issue by Derek-Ha0531** [Derek-Ha0531/github-test#1]
test111

- [ ] 1st thing to do
- [ ] 2nd thing to do
- [ ] 3rd thing to do

**Comment by Derek-Ha0531** [comment]
[(DADE) 쿠팡 뉴스룸_2월 유튜브 운영 견적서_240226_1 (1).xlsx](https://github.com/Derek-Ha0531/github-test/files/14471440/DADE._2._240226_1.1.xlsx)
